requires:
  fbl: '>=1.6.0'

pipeline:
  '--': 
    - void

    <$ if (ctx.circleci.toString() === 'true') { $>
    <$ if (ctx.docker.toString() === 'true') { $>
    - '->':
        contentFromFile: templates/.circleci/config.docker.yml
        path: <%- $.fs.getAbsolutePath(ctx.destination, cwd) %>/.circleci/config.yml
    <$ } else { $>        
    - '->':
        contentFromFile: templates/.circleci/config.node_module.yml
        path: <%- $.fs.getAbsolutePath(ctx.destination, cwd) %>/.circleci/config.yml
    <$ } $>
    <$ } $>
