version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      # install fbl
      - run: sudo npm i -g fbl

      # prepare dir
      - run: mkdir test

      - run:
          name: Git Config
          command: |
            git config --global user.email "you@example.com"
            git config --global user.name "Your Name"

      # generate project
      - run: 
          name: Generate Project
          command: |
            fbl \
              --verbose \
              -a \$.ctx.name=test \
              -a \$.ctx.license=MIT \
              -a \$.ctx.description=My\ Test \
              -a \$.ctx.author=Foo \
              -a \$.ctx.destination=./test \
              -a \$.ctx.git.init=true \
              -a \$.ctx.git.commit=true \
              -a \$.ctx.docker=true \
              ./

      # build generated plugin
      # note: `yarn install` is part of plugin generator flow, so all dependencies should already be installed
      - run:
          command: yarn build
          working_directory: ~/repo/test

      # test generated plugin
      - run:
          command: yarn test
          working_directory: ~/repo/test

      # test for outdated packages
      - run:
          command: yarn outdated
          working_directory: ~/repo/test

      # test docker build
      - setup_remote_docker
      - run:
          command: | 
            sudo docker build .
          working_directory: ~/repo/test