version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # install all app dependencies
      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # build it
      - run: yarn build

      # persist build
      - persist_to_workspace:
          root: ~/repo
          paths: .

      # run tests and generate coverage report
      - run: yarn test

      - run:
          name: Generate coverage report & send it to codecov.io
          command: |-
            # create & send only if not executed on a local box
            if [[ "$CIRCLE_BUILD_NUM"x != 'x' ]]; then
              ./node_modules/.bin/nyc report --reporter=text-lcov > ./coverage.lcov
              bash <(curl -s https://codecov.io/bash) -f ./coverage.lcov
            fi
      
      # store artifacts
      - store_artifacts:
          path: ./coverage

      - store_artifacts:
          path: ./mochawesome-report
  
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Generate .npmrc
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc

      - run:
          name: Publish package
          command: npm publish


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              ignore: /.*/